language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.8.15
  - DJANGO_VERSION=1.9.10
  - DJANGO_VERSION=1.10.2
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.9.9
    - python: "3.3"
      env: DJANGO_VERSION=1.10.2
  fast_finish: true

install:
  - pip install Django==$DJANGO_VERSION djangorestframework==3.5.1
  - pip install coverage==3.7.1
  - pip install coveralls
script:
  coverage run runtests.py
after_success:
  coveralls
