language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO='Django<2,>=1.11' DRF='djangorestframework<3.5,>=3.4'
  - DJANGO='Django<2,>=1.11' DRF='djangorestframework<3.6,>=3.5'
  - DJANGO='Django<2,>=1.11' DRF='djangorestframework<3.7,>=3.6'
  - DJANGO='Django<2,>=1.11' DRF='djangorestframework<3.8,>=3.7'
  - DJANGO='Django<2,>=1.11' DRF='djangorestframework<3.9,>=3.8'
matrix:
  fast_finish: true

install:
  - pip install "$DJANGO" "$DRF"
  - pip install coverage==3.7.1
  - pip install coveralls
script:
  coverage run runtests.py
after_success:
  coveralls
